// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldAlerts.Infrastructure.Data;

#nullable disable

namespace WorldAlerts.Infrastructure.Migrations
{
    [DbContext(typeof(WorldAlertsDbContext))]
    partial class WorldAlertsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("WorldAlerts.Domain.Entities.AlertChannel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationChannelType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("AlertChannels");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.AlertRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumSeverity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.NotificationDelivery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("WorldEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("WorldEventId");

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.WorldEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorldEvents");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.AlertChannel", b =>
                {
                    b.HasOne("WorldAlerts.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany("NotificationChannels")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("WorldAlerts.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldAlerts.Domain.Entities.WorldEvent", "WorldEvent")
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("WorldEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");

                    b.Navigation("WorldEvent");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.AlertRule", b =>
                {
                    b.Navigation("NotificationChannels");

                    b.Navigation("NotificationDeliveries");
                });

            modelBuilder.Entity("WorldAlerts.Domain.Entities.WorldEvent", b =>
                {
                    b.Navigation("NotificationDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
